UPDATE DEBITOS
SET SITUACAO_DEBITO = 'ATRASADO'
WHERE DATAVENCIMENTO < CURRENT_DATE AND SITUACAO_DEBITO NOT IN('Negociado') AND SITUACAO_DEBITO NOT IN ('Pago')

UPDATE DEBITOS
SET SITUACAO_DEBITO = 'PENDENTE'
WHERE DATAVENCIMENTO > CURRENT_DATE AND SITUACAO_DEBITO != ('Pago')

UPDATE DEBITOS 
SET DATAVENCIMENTO = ((EXTRACT(YEAR FROM DATAVENCIMENTO) -5 ) ||'-'||
(EXTRACT(MONTH FROM DATAVENCIMENTO)) ||'-'||
(EXTRACT(DAY FROM DATAVENCIMENTO)))
WHERE SITUACAO_DEBITO = 'Negociado'