--1

UPDATE DEBITOS
SET SITUACAO_DEBITO = 'ATRASADO'
WHERE DATAVENCIMENTO < CURRENT_DATE AND SITUACAO_DEBITO NOT IN('Negociado') AND SITUACAO_DEBITO NOT IN ('Pago')

--2

UPDATE DEBITOS
SET SITUACAO_DEBITO = 'PENDENTE'
WHERE DATAVENCIMENTO > CURRENT_DATE AND SITUACAO_DEBITO != ('Pago')

--3

UPDATE DEBITOS 
SET DATAVENCIMENTO = ((EXTRACT(YEAR FROM DATAVENCIMENTO) -5 ) ||'-'||
LPAD(EXTRACT(MONTH FROM DATAVENCIMENTO), 2,'0') ||'-'||
LPAD(EXTRACT(DAY FROM DATAVENCIMENTO), 2,'0'))
WHERE SITUACAO_DEBITO = 'Negociado'

--4

SELECT P.NOME, P.EMAIL, P.TELEFONE
FROM PESSOA p 

--5

SELECT  PD.NOME, PD.DESCRICAO, PD.PRECO_UNITARIO
FROM PRODUTO pd
WHERE PRECO_UNITARIO > 100.00
--6

SELECT v.ID_VENDA, V.VALOR_TOTAL, V.ID_FUNCIONARIO, V.DATA_VENDA 
FROM VENDA v 
WHERE V.DATA_VENDA BETWEEN '01-01-2024' AND '01-06-2025'

--7
SELECT P.ID_PESSOA, P.NOME, EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM p.DATA_NASCIMENTO) IDADE
FROM PESSOA p 
INNER JOIN FORNECEDOR f ON F.ID_PESSOA = P.ID_PESSOA 
LEFT JOIN PRODUTO pd ON pd.ID_FORNECEDOR = f.ID_FORNECEDOR
WHERE PD.QUANTIDADE_ESTOQUE = 0 OR PD.ID_PRODUTO IS NULL

INSERT INTO PESSOA (ID_PESSOA, NOME, EMAIL, TELEFONE, DATA_NASCIMENTO)
VALUES ('78','GUSTAVO PONTIN', 'GUSTAVO@GMAIL.COM', '18998165353', '2008-08-18')

INSERT INTO FORNECEDOR(ID_FORNECEDOR, ID_PESSOA, CNPJ)
VALUES('87', '78', '23870227000193')

--8

SELECT P.NOME, P.EMAIL , P.TELEFONE 
FROM PESSOA p 
INNER JOIN CLIENTE c ON C.ID_PESSOA = P.ID_PESSOA 
INNER JOIN DEBITOS d ON D.ID_CLIENTE = C.ID_CLIENTE
WHERE D.DATAVENCIMENTO < CURRENT_DATE
AND D.ID_DEBITO NOT IN (SELECT P2.ID_DEBITO FROM PAGAMENTO p2 WHERE P2.ID_DEBITO = D.ID_DEBITO)

--9
 
SELECT 
FROM DEBITOS d 
INNER JOIN CLIENTE c ON C.ID_CLIENTE = D.ID_CLIENTE
WHERE D.SITUACAO_DEBITO = 'ATRASADO'


SELECT  P.ID_PESSOA, P.NOME, P.EMAIL, P.TELEFONE, 
EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM p.DATA_NASCIMENTO) IDADE
FROM PESSOA p
INNER JOIN CLIENTE c ON C.ID_CLIENTE = P.ID_PESSOA
INNER JOIN DEBITOS d ON D.ID_CLIENTE = C.ID_CLIENTE





--10

UPDATE PRODUTO P  
SET P.PRECO_UNITARIO = P.PRECO_UNITARIO*0.1
WHERE P.QUANTIDADE_ESTOQUE <10

--12

UPDATE DEBITOS D
SET D.SITUACAO_DEBITO = 'PAGOS'
WHERE D.SITUACAO_DEBITO = 'ATRASADO' 
AND D.ID_DEBITO IN (SELECT P.ID_DEBITO FROM PAGAMENTO P WHERE P.ID_DEBITO = D.ID_DEBITO  )

--13

SELECT V.DATA_VENDA
FROM VENDA v 
WHERE V.DATA_VENDA BETWEEN '2023-12-01' AND '2024-01-31'

--14

SELECT P.QUANTIDADE_ESTOQUE 
FROM PRODUTO p 
WHERE P.QUANTIDADE_ESTOQUE BETWEEN 5 AND 20

--15

SELECT P.NOME, P.EMAIL, P.TELEFONE 
FROM PESSOA p 
WHERE P.NOME LIKE'A%'

--16

SELECT P.NOME, P.PRECO_UNITARIO, P.ID_PRODUTO 
FROM PRODUTO p
WHERE ID_PRODUTO NOT IN (SELECT I.ID_PRODUTO FROM ITENSVENDA i)

--17

SELECT C.ID_CLIENTE, C.ID_PESSOA, P.NOME, P2.NOME 
FROM CLIENTE c 
INNER JOIN PESSOA p ON P.ID_PESSOA = ID_CLIENTE 
INNER JOIN VENDA v ON V.ID_PESSOA = C.ID_PESSOA
LEFT JOIN ITENSVENDA i ON I.ID_ITEM_VENDA = V.ID_VENDA 
LEFT JOIN PRODUTO p2 ON P2.ID_PRODUTO = I.ID_ITEM_VENDA
WHERE 
